In [3]:
# Pandas의 기본 객체 
# series => 1차원 어레이, DataFrame => 2차원 어레이
import pandas as pd
s = pd.Series([1.5,3,5.3,7.2,9])
print(s)


0    1.5
1    3.0
2    5.3
3    7.2
4    9.0
dtype: float64
a    1.5
b    3.0
c    5.3
d    7.2
e    9.0
dtype: float64


In [5]:
# 인덱스 지정
import pandas as pd
s = pd.Series([1.5,3,5.3,7.2,9], index=['a','b', 'c','d','e'])
print(s)

a    1.5
b    3.0
c    5.3
d    7.2
e    9.0
dtype: float64


In [9]:
import numpy as np
a = np.array([1,2,3])
print(a)

# 0으로 채워진 어레이 만들기
b = np.zeros(3)
print(b)
# 1로만 채워진 어레이 만들기
c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
import numpy as np
a = np.array([1.,2.,3.,4.])
b = np.array([4.,3.,2.,1.])
# 요소별 합
print(np.add(a,b))
# 요소별 곱
print(np.multiply(a,b))
# 어레이 값의 평균
print(np.mean(a))

[5. 5. 5. 5.]
[4. 6. 6. 4.]
2.5


In [15]:
import numpy as np
# 0과 1범위에서 균일한 분포를 갖는 숫자들 샘플링
a = np.random.rand(2,5)
print(a)
# 표준정규분포를 갖는 숫자들을 샘플링
b = np.random.randn(2,5)
print(b)

[[0.52068407 0.99434676 0.60379027 0.12014538 0.6339095 ]
 [0.63677129 0.0980734  0.25915863 0.13811222 0.35052044]]
[[ 0.74226064 -0.03906425  0.76164758  0.43634985 -2.92675092]
 [ 1.45698623  1.14897934  0.04667762  1.207224    0.32230687]]


In [17]:
import numpy as np
# 파이
a = np.pi
print(a)
# 오일러 상수
b = np.e
print(b)

3.141592653589793
2.718281828459045


In [21]:
import numpy as np
a = np.array([1.2,2,3,4])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[1.2 2.  3.  4. ]
float64


In [25]:
import numpy as np
a = np.array([(1,3,4),(2,3,4),(3,5,8)], dtype = complex)
print(a)

[[1.+0.j 3.+0.j 4.+0.j]
 [2.+0.j 3.+0.j 4.+0.j]
 [3.+0.j 5.+0.j 8.+0.j]]


In [28]:
import pandas as pd
no = []
sjname = ['수학','과학','파이썬']
no.append(1)
no.append(2)
no.append(3)

subject = pd.DataFrame()
subject['과목번호']=no
subject['과목명']=sjname
print(subject)

# 엑셀파일로 저장
subject.to_excel("C:\py_test\subject.xls", index=False)
# csv확장자로 저장
subject.to_csv("C:\py_test\subject.csv", encoding="utf-8-sig", index=False)

   과목번호  과목명
0     1   수학
1     2   과학
2     3  파이썬


C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_5608/2613182555.py:13: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  subject.to_excel("C:\py_test\subject.xls", index=False)
