In [3]:
# Pandas의 기본 객체 
# series => 1차원 어레이, DataFrame => 2차원 어레이
import pandas as pd
s = pd.Series([1.5,3,5.3,7.2,9])
print(s)


0    1.5
1    3.0
2    5.3
3    7.2
4    9.0
dtype: float64
a    1.5
b    3.0
c    5.3
d    7.2
e    9.0
dtype: float64


In [5]:
# 인덱스 지정
import pandas as pd
s = pd.Series([1.5,3,5.3,7.2,9], index=['a','b', 'c','d','e'])
print(s)

a    1.5
b    3.0
c    5.3
d    7.2
e    9.0
dtype: float64


In [9]:
import numpy as np
a = np.array([1,2,3])
print(a)

# 0으로 채워진 어레이 만들기
b = np.zeros(3)
print(b)
# 1로만 채워진 어레이 만들기
c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
import numpy as np
a = np.array([1.,2.,3.,4.])
b = np.array([4.,3.,2.,1.])
# 요소별 합
print(np.add(a,b))
# 요소별 곱
print(np.multiply(a,b))
# 어레이 값의 평균
print(np.mean(a))

[5. 5. 5. 5.]
[4. 6. 6. 4.]
2.5


In [15]:
import numpy as np
# 0과 1범위에서 균일한 분포를 갖는 숫자들 샘플링
a = np.random.rand(2,5)
print(a)
# 표준정규분포를 갖는 숫자들을 샘플링
b = np.random.randn(2,5)
print(b)

[[0.52068407 0.99434676 0.60379027 0.12014538 0.6339095 ]
 [0.63677129 0.0980734  0.25915863 0.13811222 0.35052044]]
[[ 0.74226064 -0.03906425  0.76164758  0.43634985 -2.92675092]
 [ 1.45698623  1.14897934  0.04667762  1.207224    0.32230687]]


In [17]:
import numpy as np
# 파이
a = np.pi
print(a)
# 오일러 상수
b = np.e
print(b)

3.141592653589793
2.718281828459045


In [21]:
import numpy as np
a = np.array([1.2,2,3,4])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[1.2 2.  3.  4. ]
float64


In [25]:
import numpy as np
a = np.array([(1,3,4),(2,3,4),(3,5,8)], dtype = complex)
print(a)

[[1.+0.j 3.+0.j 4.+0.j]
 [2.+0.j 3.+0.j 4.+0.j]
 [3.+0.j 5.+0.j 8.+0.j]]


In [28]:
import pandas as pd
no = []
sjname = ['수학','과학','파이썬']
no.append(1)
no.append(2)
no.append(3)

subject = pd.DataFrame()
subject['과목번호']=no
subject['과목명']=sjname
print(subject)

# 엑셀파일로 저장
subject.to_excel("C:\py_test\subject.xls", index=False)
# csv확장자로 저장
subject.to_csv("C:\py_test\subject.csv", encoding="utf-8-sig", index=False)

   과목번호  과목명
0     1   수학
1     2   과학
2     3  파이썬


C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_5608/2613182555.py:13: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  subject.to_excel("C:\py_test\subject.xls", index=False)


In [15]:
# 데이터 프레임은 파이썬의 리스트와 딕셔너리의 조합
import pandas as pd
df = pd.DataFrame({"이름":["홍길동","홍길순","임꺽정"], "Age":[22,32,50], "성별":["male", "female","male"]})
# 전체 구조 출력
print(df)
# 데이터 프레임에서 성별 컬럼만 출력
print(df["성별"])
# 데이터 프레임에 고향컬럼 추가
homes = pd.Series(["조선", "대전", "서울"], name = "고향")
df["고향"] = homes

# 하나의 시리즈에 집계함수(평균, 최대값, 최소값)
print(df["Age"].max())  # 최대값 출력
print(df["Age"].min())  # 최소값 출력
print(df["Age"].mean())  # 평균값 출력



    이름  Age      성별
0  홍길동   22    male
1  홍길순   32  female
2  임꺽정   50    male
0      male
1    female
2      male
Name: 성별, dtype: object
50
22
34.666666666666664


In [18]:
# 데이터 프레임은 파이썬의 리스트와 딕셔너리의 조합
import pandas as pd
df = pd.DataFrame({"이름":["홍길동","홍길순","임꺽정"], "Age":[22,32,50], "성별":["male", "female","male"]})
# 데이터 프레임의 기본 통계 내용을 작성해서 보여줌
print(df.describe())
# head는 위에서부터 잘라온다.
print(df.head(2))  # 위에서 2개 출력
# tail은 밑에서부터 잘라온다.
print(df.tail(2))  # 밑에서 2개 출력

             Age
count   3.000000
mean   34.666667
std    14.189198
min    22.000000
25%    27.000000
50%    32.000000
75%    41.000000
max    50.000000
    이름  Age      성별
0  홍길동   22    male
1  홍길순   32  female
    이름  Age      성별
1  홍길순   32  female
2  임꺽정   50    male


In [37]:
import pandas as pd

df = pd.read_excel("order.xlsx")
print(df)
# 1. 손흥민의 주문 개수는?
is_son = df["name"] == "손흥민"
print(df[is_son]["order_no"].count())
# 2. 손흥민이 산 상품은?
print(df[is_son]["product"])
# 3. 스커트를 산 사람은?
is_skirt = df["product"]=="스커트"
print(df[is_skirt]["name"])
# 4. 가장 많이 주문한 사람의 아이디와 이름, 주문개수는? 
print(df.groupby(["user_id", "name"])["order_no"].count())
# 정렬
newdf = df.groupby(["user_id", "name"])["order_no"].count().reset_index(name = "count")
newdf = newdf.sort_values("count", ascending = False)
print(newdf)
# 5. 김지원이 사용한 총 금액은? 
is_kim = df["name"]=="김지원"
print(df[is_kim]["price"].sum())


   Unnamed: 0  order_no user_id user_pass name address product    price  brand
0           0         1   user1     pass1  손흥민      런던     운동화   100000    나이키
1           1         2   user2     pass2   설현      서울      코트   150000    버버리
2           2         3   user3     pass3   원빈      대전     반바지    30000   유니클로
3           3         4   user4     pass4  송혜교      대구     스커트    55000     자라
4           4         5   user5     pass5  소지섭      부산      코트  1100000   알레그리
5           5         6   user6     pass6  김지원      울산     티셔츠     9900   지오다노
6           6         7   user6     pass6  김지원      울산     운동화   220000     텐디
7           7         8   user1     pass1  손흥민      런던     스커트    30000  크로커다일
8           8         9   user1     pass1  손흥민      런던      코트   580000    띠어리
3
0    운동화
7    스커트
8     코트
Name: product, dtype: object
3    송혜교
7    손흥민
Name: name, dtype: object
user_id  name
user1    손흥민     3
user2    설현      1
user3    원빈      1
user4    송혜교     1
user5    소지섭     1